# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChargeSpot
                                 A QGIS plugin
 QGIS Plugin to find and visualize electric vehicle charging stations
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-20
        copyright            : (C) 2024 by ChargeSpot
        email                : contact@chargespot.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ChargeSpot class from file ChargeSpot.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Check and install dependencies
    try:
        import requests
        import reportlab
    except ImportError:
        from .dependency_installer import install_dependencies
        install_dependencies()
    
    from .charge_spot import ChargeSpot
    return ChargeSpot(iface)

